spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lime?serverTimezone=Europe/Budapest
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

server:
  port: 8081


keycloak:
  auth-server-url: http://localhost:8080/auth
  resource: Lime-Shop-app
  realm: Lime-Shop
  credentials:
    secret: 05d473ca-457c-439a-bf8e-0eed540aa3cc
  cors: true
  enabled: true


corn:
  setCanceled: "0 15 0/2 * * *"

