spring:
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  main:
    banner-mode: off

  profiles:
    active: dev

server:
  port: 8081

corn:
  setCanceled: "0 15 0/2 * * *"


