spring:
  datasource:
    url: jdbc:mysql://baza:3306/lime?serverTimezone=Europe/Budapest
    username: limeU
    password: limeP
    driver-class-name: com.mysql.cj.jdbc.Driver


keycloak:
  auth-server-url: "http://keycloak:8080/auth"
  resource: "Lime-Shop-app"
  realm: "Lime-Shop"
  credentials:
    secret: "6CNWgreUpBbKwjsl1papHDhH0UzVVjcl"
  cors: true
  enabled: true



apiKey:
  geo: ${apiKeyGeo}